---
- name: Installing Docker
  import_playbook: playbooks/installDocker.yaml

- name: Installing Kubernetes Components
  import_playbook: playbooks/installKubernetesComponents.yaml
  
- name: Initialize the Kubernetes Controle plane on master
  import_playbook: playbooks/initializing-kubernetes-master.yaml