---
- name: Install Kubernetes
  hosts: all
  become: yes
  # remote_user: ubuntu

  tasks:
  - name: Copy k8s.conf to /etc/modules-load.d/k8s.conf
    copy:
      src: kubernetes/modules-load.d_k8s.conf
      dest: /etc/modules-load.d/k8s.conf

  - name: Copy k8s.conf to /etc/sysctl.d/k8s.conf
    copy:
      src: kubernetes/modules-load.d_k8s.conf
      dest: /etc/sysctl.d/k8s.conf
    register: result
  
  - name: reload sysctl
    shell: sysctl --system
    when: result.changed

  - name: Install dependent packages
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - apt-transport-https
        - curl

  - name: Add kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  
  - name: Add the Kubernetes apt repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Installing kubeadm, kubelet and kubectl 
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: prevents upgradation of kubectl, kubeadm, kubelet
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
    - kubelet 
    - kubeadm 
    - kubectl