---
- name: Install Docker for kubernetes
  hosts: all
  become: yes
  # remote_user: ubuntu

  tasks:
  - name: Installing Dependencies & required packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add the Docker apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker CE
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      # - containerd.io=1.2.13-2
      # - docker-ce=5:19.03.11~3-0~ubuntu-{{ ansible_distribution_release }}
      # - docker-ce-cli=5:19.03.11~3-0~ubuntu-{{ ansible_distribution_release }}
      - containerd.io
      - docker-ce
      - docker-ce-cli

  - name: Setting Docker Directory
    file:
      path: /etc/docker
      state: directory

  - name: copy daemon.json to Server
    copy:
      src: docker/daemon.json
      dest: /etc/docker/daemon.json
    notify:
      - restart-docker-service

  - name: Create /etc/systemd/system/docker.service.d
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
  
  - name: Enable Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Adding permission for local User to run docker
    user:
      name: "{{ item }}"
      groups: docker
      state: present
    with_items:
    - ubuntu

  handlers:
  - name: restart-docker-service
    service:
      name: docker
      state: restarted
