- name: Attaching node to master
  hosts: all

  tasks:
  - name: create join command
    become: yes
    command: kubeadm token create --print-join-command | grep -i kubeadm > /tmp/join-command.sh
    when: inventory_hostname in groups['master']

  - name: Fetching join command script to master
    when: inventory_hostname in groups['master']
    fetch:
      src: tmp/join-command.sh
      dest: join-command.sh
      mode: 755
      flat: yes
  
  - name: copy join Command Script to Node Machine
    when: inventory_hostname in groups['nodes']
    copy:
      src: join-command-script
      dest: /tmp/join-command.sh
      mode: 755
  
  - name: Run Join Command Script
    when: inventory_hostname in groups['nodes']
    become: yes
    shell: kubeadm reset -f && /tmp/join-command.sh
    register: output

  - name: Print Join Command output
    when: inventory_hostname in groups['nodes']
    debug: var=output.stdout_lines

  - name: Checking the Join Status
    when: inventory_hostname in groups['master']
    shell: kubectl get nodes
    register: output  

  - name: Print Join Status output
    when: inventory_hostname in groups['master']
    debug: var=output.stdout_lines